name: CD

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-release@0.24
      - uses: taiki-e/install-action@cargo-make
      - name: login
        run: cargo login "$CARGO_AUTH_KEY"
        env:
          CARGO_AUTH_KEY: ${{ secrets.CARGO_AUTH_KEY }}
      - run: cargo make release
