name: checks

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: primait/shared-github-actions/actions/wait-for-status-checks@wait-for-status-checks-v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
