run-name: Run Criterion benches

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  criterion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: install criterion
        run: cargo install criterion
      - name: cargo criterion
        run: cargo criterion
      - name: Save criterion results
        uses: actions/upload-artifact@v3
        with:
          name: criterion-result
          path: target/criterion/reports/*
