[package]
name = "positional_derive"
version = "0.1.1"
edition = "2021"
description = "macros for positional crate"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.95", features = ["extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0.39"
proc-macro-error = "1.0.4"
trybuild = "1.0.61"

